#!/usr/bin/env bash
# tools.sh — 通用研究项目 shell helper
#
# 把"建笔记 / 索引 / 搜索 / 启动 spec"固化成命令。
# Agent 调脚本比让它每次重写 50 行 bash 稳定多了。
#
# 使用方法：
#   chmod +x tools.sh
#   ./tools.sh paper <slug>          # 建一份 paper 笔记
#   ./tools.sh note <title>          # 建一份 research note
#   ./tools.sh weekly                # 建本周 weekly digest
#   ./tools.sh experiment <slug>     # 建一个实验目录 + spec.yaml
#   ./tools.sh search <keyword>      # 全仓库搜索
#   ./tools.sh index                 # 重新生成各文件夹索引

set -euo pipefail

# 切到 script 所在目录（让脚本从任何地方调用都对）
cd "$(dirname "$0")"

# ---------- 配置 ----------
PAPERS_DIR="papers"
NOTES_DIR="notes"
EXPERIMENTS_DIR="experiments"
WEEKLY_DIR="weekly"
TEMPLATES_DIR="templates"

# ---------- 工具函数 ----------

usage() {
    cat <<EOF
Usage: $0 <command> [args]

Commands:
  paper <slug>          建一份 paper 笔记 papers/YYYY-<slug>.md
  note <title>          建一份研究笔记 notes/YYYY-MM-DD-<title>.md
  weekly                建本周 weekly digest weekly/YYYY-WXX.md
  experiment <slug>     建实验目录 experiments/<slug>/ + spec.yaml
  search <keyword>      全仓库搜索 markdown
  index                 重新生成各文件夹的 README 索引

Examples:
  $0 paper rope-encoding
  $0 note baseline-comparison
  $0 weekly
  $0 experiment rope-ablation
  $0 search "long context"
EOF
}

cmd_paper() {
    local slug="$1"
    local year=$(date +%Y)
    local file="$PAPERS_DIR/${year}-${slug}.md"
    local figdir="$PAPERS_DIR/${year}-${slug}"

    mkdir -p "$PAPERS_DIR" "$figdir"

    if [[ -f "$file" ]]; then
        echo "Already exists: $file"
        exit 1
    fi

    cp "$TEMPLATES_DIR/paper-note.md" "$file"
    # 替换标题占位
    sed -i.bak "s/<Paper Title>/${slug}/" "$file" && rm "${file}.bak"
    echo "Created: $file"
    echo "Figures dir: $figdir/"
}

cmd_note() {
    local title="$1"
    local date=$(date +%Y-%m-%d)
    local file="$NOTES_DIR/${date}-${title}.md"

    mkdir -p "$NOTES_DIR"

    if [[ -f "$file" ]]; then
        echo "Already exists: $file"
        exit 1
    fi

    cp "$TEMPLATES_DIR/research-note.md" "$file"
    sed -i.bak "s/<Research Note Title>/${title}/" "$file" && rm "${file}.bak"
    echo "Created: $file"
}

cmd_weekly() {
    local week=$(date +%G-W%V)
    local file="$WEEKLY_DIR/${week}.md"

    mkdir -p "$WEEKLY_DIR"

    if [[ -f "$file" ]]; then
        echo "Already exists: $file"
        exit 1
    fi

    cp "$TEMPLATES_DIR/weekly-digest.md" "$file"
    sed -i.bak "s/YYYY-WXX/${week}/" "$file" && rm "${file}.bak"
    echo "Created: $file"
}

cmd_experiment() {
    local slug="$1"
    local dir="$EXPERIMENTS_DIR/${slug}"

    if [[ -d "$dir" ]]; then
        echo "Already exists: $dir"
        exit 1
    fi

    mkdir -p "$dir/tests"
    cp "$TEMPLATES_DIR/experiment-spec.yaml" "$dir/spec.yaml"
    sed -i.bak "s/<slug-of-this-experiment>/${slug}/" "$dir/spec.yaml" && rm "$dir/spec.yaml.bak"

    # placeholder pytest
    cat > "$dir/tests/test_invariants.py" <<'PYEOF'
"""
TDD-first: 这里先列出 invariant 测试，再写实现。
跑完应该 RED → 实现后 GREEN。
"""

import pytest


def test_placeholder_invariant_1():
    """Replace with your real invariant"""
    assert True, "TODO: replace with real test"


def test_placeholder_invariant_2():
    assert True, "TODO: replace with real test"
PYEOF

    echo "Created: $dir/"
    echo "  - spec.yaml"
    echo "  - tests/test_invariants.py"
    echo ""
    echo "Next step: 编辑 $dir/spec.yaml 把 placeholder 换成你的实验"
}

cmd_search() {
    local keyword="$1"
    grep -rn --include="*.md" --include="*.yaml" --include="*.yml" \
        "$keyword" . 2>/dev/null \
        | grep -v "node_modules" \
        | grep -v ".git/"
}

cmd_index() {
    # 简化版：为 papers/ notes/ experiments/ weekly/ 各生成一份 README
    for dir in "$PAPERS_DIR" "$NOTES_DIR" "$EXPERIMENTS_DIR" "$WEEKLY_DIR"; do
        if [[ -d "$dir" ]]; then
            local readme="$dir/README.md"
            {
                echo "# $(basename "$dir") · Index"
                echo ""
                echo "_Auto-generated by \`tools.sh index\`. Do not edit by hand._"
                echo ""
                # 列出本目录的 markdown 文件
                for f in "$dir"/*.md; do
                    [[ -f "$f" && "$(basename "$f")" != "README.md" ]] || continue
                    local title
                    title=$(grep -m1 "^# " "$f" 2>/dev/null | sed 's/^# //' || echo "$(basename "$f")")
                    echo "- [${title}]($(basename "$f"))"
                done
            } > "$readme"
            echo "Indexed: $readme"
        fi
    done
}

# ---------- main dispatcher ----------

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

cmd="$1"
shift

case "$cmd" in
    paper)        [[ $# -eq 1 ]] || { usage; exit 1; }; cmd_paper "$1" ;;
    note)         [[ $# -eq 1 ]] || { usage; exit 1; }; cmd_note "$1" ;;
    weekly)       cmd_weekly ;;
    experiment)   [[ $# -eq 1 ]] || { usage; exit 1; }; cmd_experiment "$1" ;;
    search)       [[ $# -eq 1 ]] || { usage; exit 1; }; cmd_search "$1" ;;
    index)        cmd_index ;;
    *)            usage; exit 1 ;;
esac
